name: Selenium Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        testClass: [ EmployeeTest, RecruitmentTest ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Print Runner Info
        run: |
          echo "RUNNER_NAME: $RUNNER_NAME"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_ARCH: $RUNNER_ARCH"
          echo "HOSTNAME:"
          hostname
          
          # ✅ 2. اطبع الـ Public IP
      - name: Print Public IP
        run: |
          echo "Public IP:"
          curl -s ifconfig.me
          
          # ✅ 3. اطبع GitHub runner context
      - name: Print Runner Context
        run: echo '${{ toJson(runner) }}'

      #      - name: wait for selenium grid
      #        run: |
      #          for i in {1..10}; do
      #            curl -s http://localhost:4444/status && break
      #            sleep 2
      #          done

      - name: run tests
        run: mvn clean test -Dexecution.mode=remote -Dtest=${{ matrix.testClass }}

      - name: Save Machine Info
        run: |
          echo "Runner: $RUNNER_NAME" > machine-info.txt
          echo "Hostname: $(hostname)" >> machine-info.txt
          echo "IP: $(curl -s ifconfig.me)" >> machine-info.txt

      - name: Upload Machine Info
        uses: actions/upload-artifact@v4
        with:
          name: machine-info-${{ matrix.instance }}
          path: machine-info.txt
